language: java
sudo: false
install: true

jdk:
  - oraclejdk8
  
# faster builds
#gem 'coveralls', require: false 
script: #"mvn cobertura:cobertura"
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar -Dsonar.projectKey=devops-asset_sonarqube -Dsonar.organization=devops-asset -Dsonar.host.url=https://sonarcloud.io -Dsonar.token=$SONAR_TOKEN

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'

#require 'coveralls'
#Coveralls.wear!
after_success:
  - bash <(curl -s https://codecov.io/bash)
