# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pr:
- master

pool:
  vmImage: ubuntu-latest

variables:
  MAVEN_CACHE_FOLDER: $(Pipeline.Workspace)/.m2/repository
  
steps:
- script: |
    tree /home/vsts/.m2/repository
    mkdir -p /home/vsts/.m2/repository/com/fortify/cloudscan/plugins/maven/project-spec-maven-plugin/23.2.1.0010
    cp /opt/hostedtoolcache/scancentral/23.2.1/x64/Core/lib/project-spec-maven-plugin-23.2.1.0010.jar /home/vsts/.m2/repository/com/fortify/cloudscan/plugins/maven/project-spec-maven-plugin/23.2.1.0010/project-spec-maven-plugin-23.2.1.0010.jar
    cp /opt/hostedtoolcache/scancentral/23.2.1/x64/Core/resources/scancentral/maven-plugin/pom.xml /home/vsts/.m2/repository/com/fortify/cloudscan/plugins/maven/project-spec-maven-plugin/23.2.1.0010/project-spec-maven-plugin-23.2.1.0010.pom
- task: FortifyOnDemandStatic@9
  inputs:
    FortifyProjects: '$(Build.SourcesDirectory)'
    FodConnection: 'fod'
    ReleaseOptions: '0'
    ReleaseId: 143395
    EntitlementSelection: '1'
    EntitlementPreference: '2'
    OverrideScanSettings: '2'
    InProgressScanActionType: '1'
    RemediationScanPreference: '0'
    BuildType: 'mvn'
    BuildCommand: 'clean verify -Dmaven.repo.local=$(MAVEN_CACHE_FOLDER)'
    PolicyFailAction: '1'
