---
resources:
- name: resource-app
  type: git
  source:
    uri: https://github.com/tonan/simple-java-maven-app.git
    branch: concourse

jobs:
- name: job-test-app
  public: true
  plan:
  - get: resource-app
    trigger: true
  - task: run-unit-tests
    file: resource-app/tasks/run-unit-tests.yml
