apiVersion: apps/v1
kind: Deployment
metadata:
  name: project1
  labels:
    app: project1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: project1
  template:
    metadata:
      labels:
        app: project1
    spec:
      containers:
      - name: project1
        image: docker.io/maximchp/weatherapp:VERSION
        resources:
          requests:
            cpu: "500m"
        ports:
        - containerPort: 8000
      imagePullSecrets:
      - name: dockerhub-registry  
---

apiVersion: v1
kind: Service
metadata:
  name: project1-service
spec:
  type: NodePort
  selector:
    app: project1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 31000

---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
 name: project1-hpa
spec:
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: project1
 minReplicas: 1
 maxReplicas: 2
 metrics:
 - type: Resource
   resource:
     name: cpu
     target:
       type: Utilization
       averageUtilization: 50
