name: Github actions demo test executions

on:
  push:
    branches: [ master ]
  pull_requests:
    brnaches: [ master ]
  schedule:
    - cron: '0/15 * * * *'

jobs:
  build:
    runs_on: ubuntu_latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "adopt"
          cache: maven
      - name: Build with maven
        run: mvn clean install
