env:
  STACK: dotnet

on: [push]

jobs:
  build_java_maven:

    runs-on: ubuntu-latest 
    
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        if: ${{ env.STACK == 'java' }}
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'      
      - name: Build with Maven
        if: ${{ env.STACK == 'java' }}
        run: mvn --batch-mode --update-snapshots verify
        
      - name: Setup .NET 3.x
        if: ${{ env.STACK == 'dotnet' }}
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.x'
