on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

defaults:
  run:
    working-directory: ./appworkdir
    
jobs:
  build_java:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: .github/workflows/maven
