on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    runs:
      using: "composite"
      steps:
        build:
        - uses: ./.github/workflows/maven
