env:
  stack: dotnet
jobs:
  build_java_maven:
    - steps:
      - name: java
        if: ${{env.stack == 'java'}}
        - uses: actions/checkout@v2
        - name: Set up JDK 11
          uses: actions/setup-java@v2
          with:
            java-version: '11'
            distribution: 'adopt'
        - name: Build with Maven
          run: mvn --batch-mode --update-snapshots verify
      
      - name: .net
        if: ${{environment.stack == 'dotnet'}}
        run: echo "Hello, world!"
