env:
  STACK: dotnet
jobs:
  runs-on: ubuntu-latest
  build_java_maven:
  
  strategy:
    matrix:
      dotnet-version: ['3.0', '3.1.x', '5.0.x' ]
        
    steps:
    - uses: actions/checkout@v2
    - name: java
    - if: contains(['java'],env.STACK)
      name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        
        name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify
      
    - if: ${{environment.stack == '.net'}}
      name: Setup dotnet ${{ matrix.dotnet-version }}
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ matrix.dotnet-version }}
        # You can test your matrix by printing the current dotnet version

      name: Display dotnet version
      run: dotnet --version
