name: cd

on:
  push:
    branches:
      - "master"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run pipeline on pull request close
        if: github.event_name == 'pull_request' && github.event.action == 'closed'
        env:
          DOCKER_PASSWORD: ${{secrets.DOCKERHUB_PASSWORD}}
        run: |
          ssh -o StrictHostKeyChecking=no -l ubuntu 18.222.86.229 sudo docker login -u tamarshnirer -p "$DOCKER_PASSWORD" 
          ssh -o StrictHostKeyChecking=no -l ubuntu 18.222.86.229 sudo docker pull tamarshnirer/helloworld
          ssh -o StrictHostKeyChecking=no -l ubuntu 18.222.86.229 sudo docker stop $(sudo docker ps -aq) || true
          ssh -o StrictHostKeyChecking=no -l ubuntu 18.222.86.229 sudo docker rm $(sudo docker ps -aq) || true'
          ssh -o StrictHostKeyChecking=no -l ubuntu 18.222.86.229 sudo docker run --name test_container -d -p 5000:5000 tamarshnirer/helloworld
