name: cd

on:
  push:
    branches:
      - "master"
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Deploy
        env:
          DOCKER_PASSWORD: ${{secrets.DOCKERHUB_PASSWORD}}
        run: |
          ssh -o StrictHostKeyChecking=no -l ubuntu 172.31.26.62 sudo docker login -u tamarshnirer -p "$DOCKER_PASSWORD" 
          ssh -o StrictHostKeyChecking=no -l ubuntu 172.31.26.62 sudo docker pull tamarshnirer/helloworld
          ssh -o StrictHostKeyChecking=no -l ubuntu 172.31.26.62 sudo docker stop $(sudo docker ps -aq) || true
          ssh -o StrictHostKeyChecking=no -l ubuntu 172.31.26.62 sudo docker rm $(sudo docker ps -aq) || true'
          ssh -o StrictHostKeyChecking=no -l ubuntu 172.31.26.62 sudo docker run --name test_container -d -p 5000:5000 tamarshnirer/helloworld
