name: CI/CD Pipeline

on: 
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Build with Maven
      run: mvn -B package --file pom.xml
      
    - name: Test
      run: mvn test

    - name: Increase the Patch part of the jar version
      run: mvn versions:set -DnewVersion=$(mvn -Dexec.executable=echo -Dexec.args='${project.version}' exec:exec | awk -F'.' -v OFS='.' 'NF==1{print ++$NF}; NF>1{$NF++; print}')

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: docker.io/${{ secrets.DOCKERHUB_USERNAME }}/simple-java-maven-app:latest

  pull-request:
    needs: build-and-test
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Create PR
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: Increase version
        title: Increase version
        body: Increase the Patch part of the jar version.
        branch: increase-version
