name: CI/CD Pipeline

on:
  push:
    branches:
      - master

env:
  IMAGE_NAME: new-repo/simple-java-maven-app:1.0.0

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK 11 and Maven
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'adopt'
          maven-version: '3.9.3'

      - name: Increase Version Patch
        id: version
        run: |
          version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          major=$(echo $version | cut -d. -f1)
          minor=$(echo $version | cut -d. -f2)
          patch=$(echo $version | cut -d. -f3)
          new_patch=$((patch + 1))
          new_version="$major.$minor.$new_patch"
          echo "::set-output name=new_version::$new_version"

      - name: Build and Package
        run: mvn package -DskipTests

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ env.IMAGE_NAME }}
        env:
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}


