name: CI_CD_Pipeline_Using_GitHub_Actions
# uses: Romi293/simple-java-maven-app@1.0.0
on:
  push:
    branches:
      - master

env: 
  IMAGE_NAME: "romi293/java_github_actions:latest"

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: |
          docker build -t $IMAGE_NAME .

      - name: Publish to DockerHub
        run: |
          echo $DOCKERHUB_TOKEN  | docker login -u $DOCKERHUB_USERNAME --password-stdin
          docker tag $IMAGE_NAME $IMAGE_NAME
          docker push $IMAGE_NAME
  
########################################################

  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Pull image from DockerHub
        run: docker pull $IMAGE_NAME

      - name: Start Docker container
        run: docker run -d -p 8080:80 --name maven-app $IMAGE_NAME

      - name: Check if container is running
        run: docker ps -a | grep maven-app
      
      - name: Display Docker container logs
        run: docker logs maven-app

########################################################

  provision-ec2:
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
              aws-access-key-id: ${{ secrets.TF_USER_AWS_KEY }}
              aws-secret-access-key: ${{ secrets.TF_USER_AWS_SECRET }}
              aws-region: us-east-1

      # - name: Setup Terraform
      #   uses: hashicorp/setup-terraform@v2

      # - name: Terraform apply
      #   id: apply
      #   run: | 
      #     terraform init TF_create_EC2_instance/.
      #     terraform validate .
      #     terraform plan .
      #     terraform apply -auto-approve .


########################################################

  update_version:
    runs-on: ubuntu-latest

    steps:
      - name: Increase Maven version patch
        id: version
        run: |
          echo CURRENT VERSION: $(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          cd ../../.././
          mvn versions:set -DnewVersion=1.0.$(($(mvn help:evaluate -Dexpression=project.version -q -DforceStdout | 
          awk -F '.' '{print $3}')+1)) -DgenerateBackupPoms=false
          echo blabla
          echo NEW VERSION: $(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          
          

  
        # mvn -B versions:set -DnewVersion=${{ github.event.release.tag_name }} -DgenerateBackupPoms=false
