name: Dependency Scan and Fail Pipeline

on: [push]

jobs:
  snyk-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

#      - name: Set up Node.js
#        uses: actions/setup-node@v2
#        with:
#          node-version: '16'

      - name: Install dependencies
        run: sudo npm install

#      - name: Run npm audit
#        run: npm audit

      - name: Run Snyk Dependency Scan
        id: snyk-scan
        run: |
          output=$(snyk test --severity-threshold=critical)
          echo "$output"
          echo "::set-output name=exit_code::${PIPESTATUS[0]}"

      - name: Check Snyk Scan Results
        run: |
          exit_code=${{ steps.snyk-scan.outputs.exit_code }}
          if [ $exit_code -ne 0 ]; then
            echo "Dependency vulnerabilities found. Failing the pipeline."
            exit 1
          else
            echo "No dependency vulnerabilities found. Pipeline continues."
          fi
