# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java#apache-maven-with-a-settings-path

name: Continuous Integration

on:
  push

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:
    # checkout
    - uses: actions/checkout@v2
    
    # set the required runtime
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file
    
    # test
    - name: Run unit tests
      run: mvn -B test --file pom.xml

    # build
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    # version artifact
    #- name: Publish to GitHub Packages Apache Maven
    #  run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
    #  env:
    #    GITHUB_TOKEN: ${{ github.token }}
