name: Dependency Review

on:
  push:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Dependency Review
      uses: actions/dependency-review-action@v2
      with:
        fail-on-severity: critical
        allow-licenses: MIT, Apache-2.0, ISC, BSD-2-Clause, 0BSD, NOASSERTION
        base-ref: ${{ github.event.push_request.base.sha || 'main' }}
        head-ref: ${{ github.event.push_request.head.sha || github.ref }}
