name: Deploy on EKS

on:
  workflow_dispatch:
  repository_dispatch:
    types: [ deploy_eks ]
jobs:
  deploy-eks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Extract version from POM
        id: extract-version
        run: |
          VERSION=$(grep -m1 '<version>' pom.xml | sed -E 's/.*>([0-9]+\.[0-9]+\.[0-9]+)<.*/\1/')
          echo "Version from POM: $VERSION"
          echo "::set-output name=version::$VERSION"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-3

      - name: Install kubectl
        uses: azure/setup-kubectl@v1
        with:
          install-latest-version: true

      - name: Apply Kubernetes manifest
        run: |
          aws eks update-kubeconfig --name eks-terraform-project --region eu-west-3
          kubectl apply -f manifests/
          echo $VERSION
          kubectl get pods --all-namespaces
        env:
          VERSION: ${{ steps.extract-version.outputs.version }}