name: CI/CD - Build and Push Docker Image, then deploy to EC2

on:
  push:
    branches:
      # Replace with your desired branch
      - master
    # Trigers only by changes in those files/directories
    # paths:
    #   - "dockerfile"

env:
  IMAGE_NAME: joska99/java-maven
  TAG_VERSION: 0.0.${{ github.run_number }}

jobs:
  build-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Install Ansible
        run: pip install ansible

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with: # Add login credentials to the repository secrets
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PSWD }}

      - name: Build and push Docker image tag from build number
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_NAME }}:${{ env.TAG_VERSION }}

      - name: Build and push Docker image tag LATEST
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_NAME }}:latest

      # deploy:
      # runs-on: ubuntu-latest
      #   steps:
      - name: Set permissions for private key
        run: |
          echo "${{ secrets.SSH_KEY_JOSKA_EC2 }}" > joska.pem
          chmod 400 joska.pem
      - name: Deploy with Ansible
        run:
          ansible-playbook --key-file joska.pem -i '54.164.199.123,'  playbook.yaml -b

          # - name: Deploy to Server 1
      #   uses: appleboy/ssh-action@master
      #   with:
      #     host: 54.164.199.123
      #     key: ${{ secrets.SSH_KEY_JOSKA_EC2 }}
      #     username: ubuntu
      #     script: sudo docker run -d -n java-app joska99/java-maven:${{ github.run_number }}
