name: CI - Build and Push Docker Image

on:
  push:
    branches:
      # Replace with your desired branch
      - master
    # Trigers only by changes in those files/directories
    # paths:
    #   - "dockerfile"

env:
  IMAGE_NAME: joska99/java-maven
  TAG_VERSION: ${{ github.sha }}

jobs:
  build-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        # Add login credentials to the repository secrets
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PSWD }}

          # TODO: use no idempotence module to pull always latest
      - name: Build and push Docker image tag from build number
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_NAME }}:${{ env.TAG_VERSION }}

      - name: Build and push Docker image tag LATEST
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_NAME }}:latest
