name: Build and Deploy Docker Image

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
          server-id: github
          settings-path: ${{ github.workspace }}

      - name: Bump version
        id: bump
        uses: mickem/gh-action-bump-maven-version@v1

      - name: Build Docker Image
        run: |
          docker build -t roybidani/simple-java-maven-app:${{ github.sha }} .
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker push roybidani/simple-java-maven-app:${{ github.sha }}
          
      - name: Deploy to EC2
        env:
          PRIVATE_KEY: ${{ secrets.DEPLOY_SSH_KEY }}
        run: |
          echo "$PRIVATE_KEY" > deploy_key.pem
          chmod 600 deploy_key.pem
          scp -i deploy_key.pem -o StrictHostKeyChecking=no ./scripts/deployment-script.sh ec2-user@35.180.61.1:/tmp/
          # Change permissions of the deployment script on the remote server
    	  ssh -i deploy_key.pem -o StrictHostKeyChecking=no ec2-user@35.180.61.1 "chmod +x /tmp/deployment-script.sh"
    	  # Execute the deployment script
          ssh -i deploy_key.pem -o StrictHostKeyChecking=no ec2-user@35.180.61.1 "/tmp/deployment-script.sh"
          rm -f deploy_key.pem


