name: CI - Build and Push Docker Image

on:
  push:
    branches:
      # Replace with your desired branch
      - master
    # Trigers only by changes in those files/directories
    # paths:
    #   - "dockerfile"

env:
  IMAGE_NAME: joska99/java-maven
  TAG_VERSION: ${{ github.sha }}
  # VERSION: ${{ vars.VERSION }}

jobs:
  build-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}   # checkout the correct branch name
          fetch-depth: 0                # fetch the whole repo history

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        # Add login credentials to the repository secrets
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PSWD }}

      - name: Git Version
        id: version
        uses: codacy/git-version@2.7.1
      
      - name: Use the version
        run: |
          echo ${{ steps.version.outputs.version }}

      # - name: Use the previous version
      #   run: |
      #     echo ${{ steps.version.outputs.previous-version }}


      - name: Build and push Docker image tag from build number
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_NAME }}:${{ env.TAG_VERSION }}

      - name: Build and push Docker image tag LATEST
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_NAME }}:latest

      - name: Build and push Docker image tag LATEST2
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: "${{ env.IMAGE_NAME }}:${{ steps.version.outputs.version }}"
