name: CD - Deploy Docker container to EC2 with Ansible

on:
  push:
    branches:
      - master

env:
  IMAGE_NAME: joska99/java-maven
  BRANCH: master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      #* Pull github repository
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: master
          fetch-depth: 0

      #* Deploy by ansble
      - name: Run Ansible playbook
        uses: dawidd6/action-ansible-playbook@v2.6.1
        with:
          directory: ./
          playbook: playbook.yaml
          key: ${{ secrets.SSH_KEY_JOSKA_EC2 }}
          inventory: |
            [all]
            ${{ secrets.EC2_IP }}

      #* Get last Tag and increase Patch( +0.0.1 )
      - name: Git Version
        id: version
        uses: codacy/git-version@2.7.1

      #* Creates GitHub release
      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.version.outputs.previous-version }}
          name: Docker-Release ${{ steps.version.outputs.previous-version }}
