name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        file: Dockerfile
        push: true
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/simple_mav

    - name: Get version
      run: |
          current_version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "Current version: $current_version"
          version=$(echo ${current_version} | awk -F'.' '{print $1"."$2"."$3+1}')
          echo "New version: $version"
          mvn versions:set -DnewVersion=$version
    
    - name: deploy through terraform
      uses: hashicorp/setup-terraform@v3
      run: terraform init && terraform apply --auto-approve

    - name: Automated Maven Version Bump
      id: bump
      uses: mickem/gh-action-bump-maven-version@v1.0.0
