name: CI/CD - Build and Push Docker Image, then deploy to EC2

on:
  push:
    branches:
      # Replace with your desired branch
      - master
    # Trigers only by changes in those files/directories
    # paths:
    #   - "dockerfile"

env:
  IMAGE_NAME: joska99/java-maven
  TAG_VERSION: 0.0.${{ github.run_number }}

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with: # Add login credentials to the repository secrets
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PSWD }}

      - name: Build and push Docker image tag from build number
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_NAME }}:${{ env.TAG_VERSION }}

      - name: Build and push Docker image tag LATEST
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_NAME }}:latest

      - name: Deploy to Server 1
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY_JOSKA_EC2 }}
          REMOTE_HOST: 54.164.199.123
          REMOTE_USER: ubuntu
          TARGET: ./app
          run: sudo docker run joska99/java-maven:${{ github.run_number }}
