name: CI - Build and Push Docker Image

on:
  workflow_run:
    workflows: ["Versioning"]
    types:
      - completed

env:
  IMAGE_NAME: joska99/java-maven
  INNER_TAG_VERSION: ${{ github.sha }}

jobs:
  build-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}   # checkout the correct branch name
          fetch-depth: 0                # fetch the whole repo history

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PSWD }}

      #* Get last Tag and increase Patch( +0.0.1 )
      - name: Git Version
        id: version
        uses: codacy/git-version@2.7.1

      #* Push to DockerHub commit Hash
      - name: Build and push Docker image tag from build number
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_NAME }}:${{ env.INNER_TAG_VERSION }}

      #* Push to DockerHub Latest
      - name: Build and push Docker image tag LATEST
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_NAME }}:latest

      #* Push to DockerHub Last Tag + Patch ( + 0.0.1)
      - name: Build and push Docker image tag LATEST2
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: "${{ env.IMAGE_NAME }}:${{ steps.version.outputs.version }}"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          branch: master
          base: dev
          token: ${{ secrets.MY_GITHUB_TOKEN }}
          title: 'Test passed and pushed new image'
          commit-message: "CI passed succsessfuly"
          delete-branch: false

