name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-24.04
    steps:
    - name: Build the Docker image
      uses: actions/checkout@v4
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
          push: true
          tags: ${{ vars.DOCKER_USERNAME }}/simple_maven:latest
