name: CI/CD - Build and Push Docker Image, then deploy to EC2

on:
  push:
    branches:
      # Replace with your desired branch
      - master
    # Trigers only by changes in those files/directories
    # paths:
    #   - "dockerfile"

env:
  IMAGE_NAME: joska99/java-maven
  TAG_VERSION: 0.0.${{ github.run_number }}

jobs:
  build-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with: # Add login credentials to the repository secrets
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PSWD }}

      - name: Build and push Docker image tag from build number
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_NAME }}:${{ env.TAG_VERSION }}

      - name: Build and push Docker image tag LATEST
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_NAME }}:latest

      # deploy:
      # runs-on: ubuntu-latest
      #   steps:
      - name: Set permissions for private key
        run: |
          echo "${{ secrets.SSH_KEY_JOSKA_EC2 }}" > key.pem
          chmod 400 key.pem
      - name: SSH into EC2 and update container
        run: |
          ssh -o StrictHostKeyChecking=no -i key.pem ec2-user@54.164.199.123 "sudo docker run joska99/java-naven:latest"

        # - name: Deploy to Server 1
      #   uses: appleboy/ssh-action@master
      #   with:
      #     host: 54.164.199.123
      #     key: ${{ secrets.SSH_KEY_JOSKA_EC2 }}
      #     username: ubuntu
      #     script: sudo docker run -d -n java-app joska99/java-maven:${{ github.run_number }}
