name: Build and Deploy Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
          server-id: github
          settings-path: ${{ github.workspace }}

      - name: Build JAR
        run: mvn clean install

      - name: Copy Dockerfile
        run: cp /home/parallels/GithubActionProject/simple-java-maven-app/Dockerfile ${{ github.workspace }}/Dockerfile

      - name: Build Docker Image
        run: |
          docker build -t roybidani/simple-java-maven-app:${{ github.sha }} -f Dockerfile .
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker push roybidani/simple-java-maven-app:${{ github.sha }}

