name: Feature/Bugfix Pipeline

on:
  pull_request:
    branches:
      - 'master'
    types:
      - opened
      - synchronize

jobs:
  build-feature:
    if: github.actor != 'dependabot[bot]'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'adopt'
          # adoptopenjdk

      - name: Install Trivy
        run: |
          sudo apt-get update
          sudo apt-get install -y wget apt-transport-https gnupg lsb-release
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
          echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee -a /etc/apt/sources.list.d/trivy.list
          sudo apt-get update
          sudo apt-get install -y trivy

      - name: Scan Dockerfile with Trivy
        run: trivy config --exit-code 1 --severity HIGH,CRITICAL .
      
      - name: Install Snyk CLI
        run: npm install -g snyk

      - name: Authenticate Snyk
        run: snyk auth ${{ secrets.SNYK_TOKEN }}

      - name: Run Snyk to check for vulnerabilities
        run: snyk test --severity-threshold=critical

      - name: Monitor and upload Snyk results
        run: snyk monitor
  
      - name: Build with Maven
        run: mvn -B clean package

      #
      # validate: Validate the project is correct and all necessary information is available.
      # compile: Compile the source code of the project.
      # test: Test the compiled source code using a suitable unit testing framework. These tests should not require the code be packaged or deployed.
      # package: Package the compiled code in its distributable format, such as a JAR or WAR.
