name: Feature/Bugfix Pipeline

on:
  pull_request:
    branches:
      - 'feature/*'
      - 'bugfix/*'
      - 'hotfix/*'
    types:
      - opened
      - synchronize

jobs:
  build-feature:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@v1
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=Shossi_simple-java-maven-app
            -Dsonar.organization=Yossi
            -Dsonar.sources=src
            -Dsonar.tests=test
            -Dsonar.exclusions=**/node_modules/**,**/*.spec.ts

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'adopt'
          # adoptopenjdk

      - name: Build with Maven
        run: mvn -B clean package

      #
      # validate: Validate the project is correct and all necessary information is available.
      # compile: Compile the source code of the project.
      # test: Test the compiled source code using a suitable unit testing framework. These tests should not require the code be packaged or deployed.
      # package: Package the compiled code in its distributable format, such as a JAR or WAR.