name: ci/cd
on:
  push:
    branches:
      - development

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.4.3
      - name: Build
        run: docker build -t image .

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.3
      - name: Run Docker container
        id: docker-run
        run: |
          output=$(sudo docker run -it 3a91)
          echo "::set-output name=output::$output"
        shell: bash

      - name: Check Container Output
        run: |
          if [[ "${{ steps.docker-run.outputs.output }}" == "Hello World!" ]]; then
            echo "Output is correct!"
          else
            echo "Output is not correct!"
          fi
        shell: bash
