name: ci

on:
  push:
    branches:
      - "development"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: tamarshnirer
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build
        run: 
          sudo docker build -t tamarshnirer/helloworld .
        
      - 
       name: Run Docker container
       id: docker-run
       run: |
         sudo docker run -d --name helloworld tamarshnirer/helloworld
         output=$(sudo docker logs helloworld)
         echo "::set-output name=output::$output"
         
      - 
       name: Check Container Output
       run: |
            if [[ "${{ steps.docker-run.outputs.output }}" == "Hello World!" ]]; then
              echo "Output is correct!"
            else
              echo "Output is not correct!"
            fi
