name: Increment Patch Version and Build Jar
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Java 11
        uses: actions/setup-java@v2
        with:
          java-version: 11

      - name: Increment Patch Version
        id: version
        run: |
          CURRENT_VERSION=$(mvn -q -Dexec.executable='echo' -Dexec.args='${project.version}' --non-recursive exec:exec)
          NEXT_VERSION=$(echo $CURRENT_VERSION | awk -F. '{$NF = $NF + 1;} 1' | sed 's/ /./g')
          echo "::set-output name=next_version::$NEXT_VERSION"

      - name: Build Jar
        run: mvn package

      - name: Rename Jar File
        run: |
          NEXT_VERSION=${{ steps.version.outputs.next_version }}
          mv target/my-app-1.0-SNAPSHOT.jar target/my-app-$NEXT_VERSION.jar

      - name: Publish Jar Artifac
        uses: actions/upload-artifact@v2
        with:
          name: my-app-jar
          path: target/my-app-$NEXT_VERSION.jar
