name: ci

on:
  push:
    branches:
      - "development"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: tamarshnirer
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build
        run: 
          sudo docker build -t tamarshnirer/helloworld .
        
      - 
       name: Run Docker container
       run: |
         sudo docker run -d --name helloworld tamarshnirer/helloworld
         sleep 5  
         docker ps 
         docker logs helloworld || true 
         docker stop helloworld || true
      
      -
       name: Update patch
       env:
         TAG: ${{vars.TAG}}
       run: |
          IFS='.' read -ra version_parts <<< "$TAG"
          ((version_parts[2]++))
          new_version="${version_parts[0]}.${version_parts[1]}.${version_parts[2]}"
          echo "$TAG=$new_version" >> $GITHUB_ENV

      -
       name: Add tag
       env:
         TAG: ${{vars.TAG}}
       run: docker tag tamarshnirer/helloworld tamarshnirer/helloworld:$TAG
      - 
        name: Log in to Docker Hub
        env:
          DOCKER_USER: tamarshnirer
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: |
          docker login -u tamarshnirer -p $DOCKER_PASSWORD 
      -
       name: Push to Dockerhub
       run: docker push tamarshnirer/helloworld
     
      -
       name: Add tag
       uses: richardsimko/update-tag@v1
       with:
         tag_name: ${{vars.TAG}}
       env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       

     
