name: gitleaks
on: push
jobs:
  scan:
    name: gitleaks
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'
    - uses: gitleaks/gitleaks-action@v2
      env:
          #GITLEAKS_CONFIG: config/.gitleaks.toml
          GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE}}
