name: CI/CD Pipeline

on:
  push:
    branches:
      - master

env:
  IMAGE_TAG: latest
#  GHCR_USERNAME: ${{ secrets.GHCR_USERNAME }}
#  GHCR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  PATCH_VERSION_SCRIPT: ./update_version.sh
  IMAGE_NAME: hello-world
  REPO_NAME: simple-java-maven-app 

jobs:
  increment-and-build-and-deliver:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Test with Maven
        run: docker build -f Dockerfile --target maven-test .
        
      - name: Build with Maven
        run: docker build -t ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} -f Dockerfile --target builder .

      - name: Update Patch Version
        run: |
          chmod +x $PATCH_VERSION_SCRIPT
          $PATCH_VERSION_SCRIPT

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Deliver to GitHub Container Registry
        run: |
          docker push ghcr.io/caesarh287/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

