name: CI/CD Pipeline

on:
  push:
    branches:
      - master

env:
  IMAGE_TAG: latest
#  GHCR_USERNAME: ${{ secrets.GHCR_USERNAME }}
#  GHCR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#  PATCH_VERSION_SCRIPT: ./update_version.sh
  IMAGE_NAME: ghcr.io/caesarh287/hello-world
#  REPO_NAME: simple-java-maven-app 

jobs:
  build-and-deploy:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - uses: docker-practice/actions-setup-docker@master
        timeout-minutes: 5
      - run: |
          set -x
          docker version
          docker run --rm hello-world

      - name: Test with Maven
        run: docker build --target maven-test .
        
      - name: Build with Maven
        run: docker build --target production -t ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} .

#      - name: Update Patch Version
#        run: |
#          chmod +x $PATCH_VERSION_SCRIPT
#          $PATCH_VERSION_SCRIPT
          
      - name: Update Patch Version
        id: update
        uses: nnichols/maven-version-bump-action@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Login to GitHub Container Registry
        run: docker login ghcr.io --username ${{ github.actor }} --password ${{ secrets.GITHUB_TOKEN }}
          
      - name: Deliver to GitHub Container Registry
        run: docker push ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

