name: Build and Push Docker Image to Docker Hub

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:


env:
  REGISTRY: docker.io
  IMAGE: maximchp/weatherapp
  TF_LOG: INFO
  TF_INPUT: false
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  BUCKET_TF_STATE: ${{ secrets.BUCKET_TF_STATE}}

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Version
      id: version
      run: |
        output=$(bash generate_version.sh head=1 build=${{ github.run_number }})
        echo "VERSION=${output}" >> $GITHUB_ENV

    - name: Auth to GH registry
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_PASS }}
            
    - name: Build, tag, and push image to DH
      id: build-image
      env:
        DH_REGISTRY: $REGISTRY
        IMAGE_TAG: $VERSION
      run: |
        docker buildx build \
          --build-arg VERSION=$VERSION \
          -t $IMAGE:$VERSION .
        docker push $IMAGE:$VERSION
        echo "image=$IMAGE:$VERSION" >> $GITHUB_OUTPUT

    - name: Setup Terraform with specified version on the runner
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.3.0
     
    - name: Terraform init
      id: init
      run: terraform init -backend-config="bucket=$BUCKET_TF_STATE"

    - name: Terraform format
      id: fmt
      run: terraform fmt -check
   
    - name: Terraform validate
      id: validate
      run: terraform validate
  
        

