name: Build and Deploy

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'


      - name: Build and Increment Version
        run: |
          # Build the project
          mvn clean install
          
      # Increment the patch version
      - name: Update Version
        id: update_version
        run: |
          # Get the current version from the pom.xml file
          current_version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "Current Version: $current_version"

          # Increment the version number
          IFS='.' read -ra version_parts <<< "$current_version"
          patch_version=$((version_parts[2] + 1))
          new_version="${version_parts[0]}.${version_parts[1]}.$patch_version"
          echo "New Version: $new_version"

          # Update the version in the pom.xml file
          mvn org.codehaus.mojo:versions-maven-plugin:2.8.1:set -DnewVersion=$new_version -DgenerateBackupPoms=false

          # Output the new version
          echo "::set-output name=version::$new_version"

      - name: Print Version
        run: |
          echo "Updated Version: ${{ steps.update_version.outputs.version }}"
