name: Maven CI/CD

on:
 push:
    branches: [ master ]
 pull_request:
    branches: [ master ]

jobs:
  build_and_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17

    - name: Build with Maven
      run: mvn package  # Replace with your Maven build command

    - name: Upload Release Asset
      uses: actions/upload-artifact@v2
      with:
        name: my-app.jar  # Set the name of your artifact file
        path: target/my-app.jar  # Set the path to your built artifact file
