name: CI/CD Pipeline

on:
  push:
    branches:
      - master

env:
  IMAGE_TAG: latest
  IMAGE_NAME: ghcr.io/caesarh287/hello-world
  PROD_IP: 52.90.41.120


jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Update Patch Version
        id: update
        uses: nnichols/maven-version-bump-action@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Test with Maven
        run: docker build --target maven-test .
        
      - name: Build with Maven
        run: docker build --target production -t ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} .
                  
      - name: Login and Publish to GitHub Container Registry
        run: |
          docker login ghcr.io --username ${{ github.actor }} --password ${{ secrets.GITHUB_TOKEN }}
          docker push ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

      - name: Deploy to EC2 with SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ env.PROD_IP }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo docker kill prod-app &>/dev/null || true
            sudo docker rm prod-app &>/dev/null || true
            sudo docker pull ghcr.io/caesarh287/hello-world
            sudo docker run -d --name prod-app ${{ env.IMAGE_NAME }}


