name: Build and Push Docker Image to Docker Hub

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:


env:
  REGISTRY: docker.io
  IMAGE: maximchp/weatherapp
  TF_LOG: INFO
  TF_INPUT: false
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  BUCKET_TF_STATE: ${{ secrets.BUCKET_TF_STATE}}

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Read head from file
      id: read_head
      run: |
        head=$(cat head)
        echo "HEAD=${head}" >> $GITHUB_ENV
    
    - name: Determine head
      id: determine_head
      run: echo "HEAD=$((HEAD + 1))" >> $GITHUB_ENV
      if: github.ref == 'refs/heads/master' # Increment head only for builds on master/main
    
    - name: Version
      id: version
      run: |
        output=$(bash generate_version.sh head=${{ env.HEAD }} build=${{ github.run_number }})
        echo "VERSION=${output}" >> $GITHUB_ENV
        echo "${output}" > version

    - name: Auth to GH registry
      uses: docker/login-action@v1
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_PASS }}
            
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.IMAGE }}

    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: |
          ${{ env.IMAGE }}:${{ env.VERSION }}
        build-args: |
          "VERSION=${{ env.VERSION }}"
        cache-from: type=gha
        cache-to: type=gha,mode=max
        #add ARG VERSION to Dockerfile

    - name: Setup Terraform with specified version on the runner
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.3.0
     
    - name: Terraform init
      id: init
      run: terraform init -backend-config="bucket=$BUCKET_TF_STATE"

    - name: Terraform format
      id: fmt
      run: terraform fmt -check
   
    - name: Terraform validate
      id: validate
      run: terraform validate
  
        

