name: learn-github-actions

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn package
        
      - name: Test
        run: mvn test        

      - name: Extract patch version
        run: |
          export PATCH_VERSION=$(xmlstarlet sel -t -v "/project/version" pom.xml | cut -d. -f3)
          echo "PATCH_VERSION=$PATCH_VERSION" >> $GITHUB_ENV
      
      - name: Update pom.xml
        run: |
          NEW_VERSION="1.2.$((PATCH_VERSION + 1))"
          sed -i "s/<version>.*<\/version>/<version>$NEW_VERSION<\/version>/" pom.xml

