name: CI/CD Pipeline

on:
  push:
    branches:
      - master
      - feature

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Fetch all branches and tags
        run: git fetch --prune --unshallow

      - name: Determine Branch and Commit Count
        id: determine_branch
        run: |
          BRANCH=$(echo "${{ github.ref }}" | awk -F'/' '{print $NF}')
          CURRENT_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          MAJOR_VERSION=$(echo $CURRENT_VERSION | cut -d'.' -f1)
          MINOR_VERSION=$(echo $CURRENT_VERSION | cut -d'.' -f2)
          PATCH_VERSION=$(echo $CURRENT_VERSION | cut -d'.' -f3)
          COMMIT_COUNT=$(git rev-list --count HEAD)
          if [ "$BRANCH" = "master" ]; then
            echo "::set-output name=version::$(($MAJOR_VERSION + 1)).0.0"
          elif [[ "$BRANCH" == "feature"* ]]; then
            echo "::set-output name=version::$MAJOR_VERSION.$(($MINOR_VERSION + 1)).0"
          elif [[ "$BRANCH" == "fixes"* ]]; then
            echo "::set-output name=version::$MAJOR_VERSION.$MINOR_VERSION.$(($PATCH_VERSION + 1))"
          else
            echo "::error::Unsupported branch"
            exit 1
          fi

      - name: Increment Version
        run: mvn -B versions:set -DnewVersion=${{ steps.determine_branch.outputs.version }} -DgenerateBackupPoms=false

      - name: Build Docker Image
        run: |
          docker build -t simple-java-maven-app:latest --build-arg RUN_NUMBER=${{ steps.determine_branch.outputs.version }} .
          
      - name: Push Docker Image
        run: |
          docker login -u ${{ secrets.DOCKER_EMAIL }} -p ${{ secrets.DOCKER_HUB }}
          docker tag simple-java-maven-app:latest denisiuss/simple-java-maven-app:latest
          docker push denisiuss/simple-java-maven-app:latest
  
