name: Java CI with Maven and Docker Operations

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-scan:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    
    # Dependency scan with Snyk and set a threshold for failing the pipeline for high severity issues
    - name: Snyk to scan for vulnerabilities
      uses: snyk/actions/maven@master
      with:
        args: --severity-threshold=high
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
    
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    # Assuming Dockerfile in the project root directory
    - name: Build Docker image
      run: docker build . -t ${{ secrets.DOCKERHUB_USERNAME }}/simpleapp:${{ github.run_number }}

    # Scan the Docker image with Snyk
    - name: Scan Docker image with Snyk
      uses: snyk/actions/docker@master
      with:
        image: ${{ secrets.DOCKERHUB_USERNAME }}/simpleapp:${{ github.run_number }}
        args: --severity-threshold=high
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
    
    # Push Docker image only if previous steps are successful
    - name: Push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/simpleapp:${{ github.run_number }}
        push: true

    # Placeholder for signing command. You must replace this with your actual image signing tool command.
    - name: Sign Docker Image
      run: echo "Placeholder for actual image signing command"
      if: success() # This step will run only if the previous steps were successful.
