name: Java CI with Maven and Docker Operations

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 20
        uses: actions/setup-java@v2
        with:
          java-version: '20'
          distribution: 'adopt'

      - name: Maven Build
        run: mvn clean install

      # Scan Dockerfile with Snyk before building the image (Preventive measure)
      - name: Scan Dockerfile with Snyk
        uses: snyk/actions/docker@master
        with:
          image: ${{ secrets.DOCKERHUB_USERNAME }}/simpleapp:latest
          command: test --file=Dockerfile
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker image
        run: |
          export DOCKER_CONTENT_TRUST=1
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/simpleapp:latest .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/simpleapp:latest
        env:
          DOCKER_CONTENT_TRUST_ROOT_PASSPHRASE: ${{ secrets.DOCKER_CONTENT_TRUST_ROOT_PASSPHRASE }}
          DOCKER_CONTENT_TRUST_REPOSITORY_PASSPHRASE: ${{ secrets.DOCKER_CONTENT_TRUST_REPOSITORY_PASSPHRASE }}

      # Only run SonarCloud analysis on merge to the main branch
      - name: SonarCloud Scan
        if: github.ref == 'refs/heads/main'
        uses: SonarSource/sonarcloud-github-action@master
        with:
          projectKey: eilaytal_simple-java-maven-app
          organization: eilaytal
          sonarToken: ${{ secrets.SONAR_TOKEN }}
