name: Maven Package

on:
  push:
    branches:
      - main
      - '**' # This will trigger the workflow for pushes to any branch

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    env:
      DOCKER_REPO: ${{ secrets.DOCKER_USERNAME }}/my-app

    steps:
    - uses: actions/checkout@v4

    - name: Get the version from the tag
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Publish to GitHub Packages Apache Maven
      run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: |
          ${{ env.DOCKER_REPO }}:latest
          ${{ env.DOCKER_REPO }}:${{ steps.get_version.outputs.VERSION }}

    - name: Image digest
      run: echo ${{ steps.build-push.outputs.digest }}
