# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: GitHub Actions CI/CD

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step to determine the current version
      - name: Read current version
        id: current_version
        run: |
          current_version=$(cat version.txt)
          echo "Current version: $current_version"
          echo "::set-output name=current_version::$current_version"

      # Step to determine which branch was merged
      - name: Determine branch merged
        id: merged_branch
        run: |
          if [[ "${{ github.event.before }}" == "refs/heads/dev" ]]; then
            echo "name=branch_type::major" >> $GITHUB_OUTPUT
          elif [[ "${{ github.event.before }}" != "refs/heads/dev" ]]; then
            echo "name=branch_type::minor" >> $GITHUB_OUTPUT
          fi

      # Step to increment the version
      - name: Increment version
        id: new_version
        run: |
          current_version="${{ steps.current_version.outputs.current_version }}"
          IFS='.' read -ra ver <<< "$current_version"
          major=${ver[0]}
          minor=${ver[1]}
          patch=${ver[2]}
          branch_type="${{ steps.merged_branch.outputs.branch_type }}"

          if [[ $branch_type == "major" ]]; then
            major=$((major + 1))
            minor=0
            patch=0
          elif [[ $branch_type == "minor" ]]; then
            minor=$((minor + 1))
            patch=0
          fi

          new_version="$major.$minor.$patch"
          echo "New version: $new_version"
          echo $new_version > version.txt
          echo "new_version=$new_version" >> $GITHUB_OUTPUT

      # Step to commit and push the new version file
      - name: Commit and push new version
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "actions@github.com"
          git add version.txt
          git commit -m "Bump version to ${{ steps.new_version.outputs.new_version }}"
          git push



      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

          
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          build-args: VERSION=${{ steps.new_version.outputs.new_version }}
          context: .
          push: true
          tags: ${{ env.DOCKER_REPO }}:${{ env.IMAGE_NAME }}-${{ steps.new_version.outputs.new_version }}
        env:
          IMAGE_NAME: simple-maven
          DOCKER_REPO: zivgl66/ziv-repo

