name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '17'

      - name: Set up Maven
        uses: actions/setup-java@v2
        with:
          distribution: 'maven'
          maven-version: '3.8.1'

      - name: Bump version
        id: bump-version
        run: |
          echo "Bumping patch version..."
          version=$(cat version.txt)
          IFS='.' read -r -a parts <<< "$version"
          parts[2]=$((parts[2] + 1))
          new_version="${parts[0]}.${parts[1]}.${parts[2]}"
          echo $new_version > version.txt
          echo "New version: $new_version"
          echo "version=$new_version" >> $GITHUB_ENV

      - name: Build JAR file
        run: |
          mvn versions:set -DnewVersion=$GITHUB_ENV.version
          mvn clean package -DskipTests

      - name: Build Docker image
        run: |
          docker build -t myapp:$GITHUB_ENV.version .

      - name: Log in to Docker Hub
        uses: docker/login-action@v2

      - name: Push Docker image to Docker Hub
        run: |
          docker tag myapp:$GITHUB_ENV.version lalush123/myapp:$GITHUB_ENV.version
          docker push ${{ secrets.DOCKER_USERNAME }}/myapp:$GITHUB_ENV.version
