name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build-jar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          # adoptopenjdk

      - name: Build with Maven
        run: mvn -B clean package

      - name: Increment Maven version
        run: mvn versions:set -DnewVersion=1.0.$(($(mvn help:evaluate -Dexpression=project.version -q -DforceStdout | sed 's/-.*//' | awk '{print int($0)}') + 1))

      - name: Commit version change
        run: |
          if git diff --quiet; then
          echo "No changes to commit"
          else
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -am "Increment version"
          git push
          fi

  build-push-docker:
    needs: build-jar
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: yossizxc/java:my-app
####
#      - name: Run Docker container
#        run: docker run -d --name my-app yossizxc/java:my-app
#
#      - name: Show containers
#        run: docker ps
#
#      - name: Verify my-app
#        run: docker exec my-app ls /app