name: maven-private-artifactory
 
on:
  push:
    branches: [ master ]
    
  pull_request:
    branches: [ master ]
  workflow_dispatch:
 
jobs:
  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v2
    
 
    - name: Set up our custom Artifactory instance
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt' # running setup-java again overwrites the settings.xml
        java-version: '11'
        #server-id: artifactory-server # value of repository/id field of the pom.xml
        #server-username: ARTIFACTORY_TOKEN_REF  # env variable name for username of Artifactory server; value can be anything as it is a transient user
        #server-password: ARTIFACTORY_TOKEN_REF # env variable name for Artifactory access token
        settings-path: ${{ github.workspace }}/.m2 # after running this action, the <username> tag contains ${env.ARTIFACTORY_USERNAME_REF} and <password> contains ${env.ARTIFACTORY_TOKEN_REF}
        overwrite-settings: false
    - name: Build with Maven
      run: mvn --settings YourOwnSettings.xml package
      env:
        # assign the environment variable env.ARTIFACTORY_TOKEN_REF with the previously configured ARTIFACTORY_TOKEN
        ARTIFACTORY_TOKEN_REF: ${{ secrets.ARTIFACTORY_TOKEN }}
        # assign the environment variable env.ARTIFACTORY_USERNAME_REF with the previously configured ARTIFACTORY_USERNAME
        ARTIFACTORY_USERNAME_REF: ${{ secrets.ARTIFACTORY_USERNAME }}
