name: Pull Request to Master Pipeline

on: 
  pull_request:
    branches: [ master ]

jobs:
  pull-request:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Create PR
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: Increase version
        title: Increase version
        body: Increase the Patch part of the jar version.
        branch: increase-version

