name: snyk-testing
on:
  repository_dispatch:
    types: [build_workflow]
  workflow_dispatch:
    inputs:
      branch:
        description: Branch name
        required: true
        default: dev
      deploy_message:
        description: Deploy Description
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install Snyk CLI (Ubuntu/macOS)
        if: ${{ matrix.os != 'windows' }}
        run: sudo npm install -g snyk
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/maven-3-jdk-11@master
      
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
          SNYK_CLI_EXECUTABLE: /usr/local/bin/snyk
          SNYK_DOWNLOAD_DESTINATION: "downloads/snyk"
        with:
          args: --severity-threshold=high
