name: TruffleHog OSS
on: [push, pull_request]
jobs:
  scanning:
    name: TruffleHog scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      #  with:
      #   fetch-depth: 0 # fetch all history so multiple commits can be scanned
      - name: TruffleHog OSS
        uses: trufflesecurity/trufflehog@main
        with:
          base: ${{ github.event.before }}
          head: HEAD
          extra_args: --debug --only-verified 
