name: Versioning

on: [push]

jobs:
  versioning_job:
    runs-on: ubuntu-latest

    name: RainMachine Parsers versioning
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Git Version
        id: version
        uses: codacy/git-version@2.7.1

      - name: Create local changes
        run: |
            echo "tag_version: ${{ steps.version.outputs.version }}" > .env

      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
            github_token: ${{ secrets.GITHUB_TOKEN }}

    #   - name: Use the version
    #     run: |
    #       echo ${{ steps.version.outputs.version }}

    #   - name: Use the previous version
    #     run: |
    #       echo ${{ steps.version.outputs.previous-version }}